### ISSUE TITLE
chore(web): non-fatal i18next `i.resolve is not a function` on genius detail pages

### ISSUE THREAD

**Issue by kurone-kito** [kurone-kito/dantalion-web-demo#79]
## Background

While verifying the GH Pages deploy for the #64 E2E roadmap follow-ups (#72 / #74), a non-fatal but reproducible `pageerror` surfaces on every prerendered genius detail page. The DOM still renders the correct content (all 34 E2E specs pass, the manual production probe passes), but every page-load reports an uncaught `TypeError` in the console.

This is **pre-existing** and **not** introduced by #72 / #74 — reverting `packages/web/src/lib/dantalion.ts` to its pre-#74 state (3 commits before HEAD) reproduces the same error against the same routes. It is a latent issue worth catching here before it starts masking real regressions.

## Reproduction

```bash
pnpm --filter @kurone-kito/dantalion-web-demo-web run build
pnpm --filter @kurone-kito/dantalion-web-demo-web run preview &
# then in a headless browser, visit any of:
#   http://127.0.0.1:4173/dantalion/en/100/
#   http://127.0.0.1:4173/dantalion/ja/919/
#   http://127.0.0.1:4173/dantalion/100.html
```

`pageerror` fires once per load with the same stack:

```
TypeError: i.resolve is not a function
  at r (dantalion-XN8HyjQm.js:3:41036)
  at dantalion-XN8HyjQm.js:3:41445
  at Sn.loadResources (dantalion-XN8HyjQm.js:3:39286)
  at a (dantalion-XN8HyjQm.js:3:41425)
  at Sn.changeLanguage (dantalion-XN8HyjQm.js:3:41789)
```

The frames are minified i18next — `Sn` is the `I18n` class. `changeLanguage` → `loadResources` → an internal backend chain whose first link calls `i.resolve(...)`, but `i` here has no `resolve` method. i18next is initialized with the inline `resources` map from `dantalion-i18n/dist/resources/createTAsync.js` and **no backend plugin**, yet `loadResources` still walks the backend chain.

`/dantalion/100.html` also emits a second, downstream error during the React-style hydration (likely fallout from the first failure, included for completeness):

```
TypeError: e.detail is not iterable (cannot read property undefined)
  at ia (dantalion-XN8HyjQm.js:3:1160)
  at Il (dantalion-XN8HyjQm.js:3:1791)
  at Ll (dantalion-XN8HyjQm.js:3:2240)
  at ch (dantalion-XN8HyjQm.js:72:838)
  at async Hh (dantalion-XN8HyjQm.js:72:865)
```

## Trigger path

Likely chain — to be confirmed:

1. `getAccessorsFor(language)` in `packages/web/src/lib/dantalion.ts` calls `createAccessorsAsync(language)` (dantalion-i18n).
2. `createAccessorsAsync` calls `createTAsync({ lng, resources })`, which calls `i18next.init({ lng, resources })`.
3. After the first `init`, subsequent `init` calls in i18next v26 delegate to `changeLanguage(lng)` internally.
4. `changeLanguage` queues a `loadResources` task that walks the backend chain even when the resources are inline. The chain's first link expects a `.resolve()` method, hits a stub object, throws.

This bug pre-dates the #74 fix because `[lang].tsx`'s `createEffect(() => persistLanguageSelection(language()))` already drives at least one EN ↔ JA switch path during hydration, even with the old per-language accessors cache.

## Acceptance criteria

- Visiting any of `/dantalion/<en|ja>/<genius>/`, `/dantalion/<N>.html`, and `/dantalion/<en|ja>/result/<triple>/` produces **zero** `pageerror` events.
- DOM content stays identical (no regression of #62 / #74 / the per-locale parity assertions in `e2e/ssg-i18n.spec.ts`).
- An e2e regression guard is added — either an explicit `pageerror` listener in the existing specs (`expect(errors).toEqual([])`) or a new `e2e/console-errors.spec.ts` that fails the suite if any prerendered route emits a `pageerror`.
- `pnpm --filter @kurone-kito/dantalion-web-demo-web run test:e2e` passes (currently 34 passed).
- `pnpm lint` / `pnpm test` / `pnpm --filter @kurone-kito/dantalion-web-demo-web run build` exit zero.

## Candidate fix surfaces

1. **Initialize i18next once with both locales and use `getFixedT(lng)`** — `createAccessorsAsync` could call `i18next.init` only on the first call and switch language via `getFixedT` thereafter, sidestepping `changeLanguage` and its backend chain. Requires patching dantalion-i18n upstream or wrapping it locally.
2. **Suppress the spurious backend chain** — pass `init({ ..., partialBundledLanguages: true, initImmediate: false })` or an empty `backend: { type: 'backend', read: (l, n, cb) => cb(null, {}) }` so `loadResources` short-circuits.
3. **Audit `[lang].tsx`'s `persistLanguageSelection`** — confirm it does not transitively call into i18next during hydration, since that is the path that triggers the language switch on detail pages.

Strategy 1 is the durable fix and would also remove the implicit per-call `i18next.init` introduced by #74; the test:e2e suite's existing per-locale parity coverage is enough to verify equivalence.

## Environment

- Reproduces against `kurone-kito.github.io/dantalion/` deploy from PR #78.
- Reproduces against local `pnpm run build && pnpm run preview`.
- Node 24 (CI) and Node 26 (local). Chromium via Playwright `@playwright/test@1.60.0`.
- `@kurone-kito/dantalion-core@1.0.0-rc.0`, `@kurone-kito/dantalion-i18n@1.0.0-rc.0`, `@solidjs/start@1.3.2`, `@solidjs/router@0.16.1`, `solid-js@1.9.13`, `vinxi@0.5.11`.

## References

- Production verification thread that surfaced this: `#64` → #78 deploy.
- Related: `#62` (the original SSR i18n leak that motivated `crawlLinks: false`), `#74` (the recent legacy-alias fix), `#67` / `#68` (E2E specs that pass content-wise despite the runtime error).
- Upstream resolver: [`@kurone-kito/dantalion-i18n@1.0.0-rc.0/dist/resources/createTAsync.js`](https://github.com/kurone-kito/dantalion-i18n).

**Comment by kurone-kito** [comment]
```
marker: dantalion-web-demo
claim-id: c79-1779592078
branch: issue/79-fix-web-i18next-changelanguage-pageerror
status: claimed
```

**Comment by kurone-kito** [comment]
_claude-idd-fork-20260920: issue claim — IDD automation marker. Do not edit._

**Comment by kurone-kito** [comment]
**IDD B2 plan (draft)**

Reproduced live with a headless Chromium against a real `build && preview`: `TypeError: i.resolve is not a function` fires on `/en/100/`, `/ja/919/`, and `/100.html`, matching the issue exactly. Root cause confirmed by reading `@kurone-kito/dantalion-i18n@1.0.0-rc.0`'''s `createTAsync.js`: every `getAccessorsFor()` call does a fresh `i18next.init()` against the i18next default-export singleton. i18next v26'''s `init()` on an already-initialized instance internally delegates to `changeLanguage()` -> `loadResources()`, which walks a backend-chain stub lacking `.resolve()` since no backend plugin is registered (only inline `resources`).

Fix stays entirely in this repo (dantalion-web-demo), not upstream dantalion-i18n:

- `initResources()` in dantalion-i18n always bundles **both** `en` and `ja` translations into the resources map regardless of the requested `lng`, so after the *first* successful `i18next.init()` call, every locale'''s data is already loaded in memory.
- Change `getAccessorsFor()` in `packages/web/src/lib/dantalion.ts` to call `createAccessorsAsync()` (the real `i18next.init()` path) only once, on first use. Every call after that builds the accessors from `i18next.getFixedT(language)` (a pure read against already-loaded resources, added as a direct `i18next` dependency of `packages/web` since dantalion-i18n resolves the same singleton via node module resolution) plus the already-exported `createAccessors(t)` helper -- never calling `i18next.init()`/`changeLanguage()` again.
- Add `i18next` (pinned `26.2.0`, matching the version dantalion-i18n resolves) as an explicit dependency of `packages/web/package.json` to avoid a phantom-dependency import.
- Add an e2e regression guard: a `page.on('''pageerror''')` listener asserting zero errors across the genius detail routes, the legacy `/<N>.html` alias, and a result-triple route, per the issue'''s acceptance criteria.

Verification: rerun the manual repro script for the before/after diff, then `pnpm --filter @kurone-kito/dantalion-web-demo-web run test:e2e`, plus `pnpm lint`/`pnpm test`/`pnpm --filter @kurone-kito/dantalion-web-demo-web run build`.

**Comment by kurone-kito** [comment]
**IDD B2 plan (final after critique)**

Critique found one gap in the draft: a naive '''only call createAccessorsAsync once''' boolean flag races if two callers request different languages before the first `i18next.init()` resolves (plausible during SSR/prerender fan-out). Refined to a single shared promise every caller awaits:

```ts
let sharedInit: Promise<{ accessors: Accessors; language: SupportedLanguage }> | null = null;

const getAccessorsFor = async (language: SupportedLanguage): Promise<Accessors> => {
  sharedInit ??= createAccessorsAsync(language).then((accessors) => ({ accessors, language }));
  const first = await sharedInit;
  if (first.language === language) return first.accessors;
  const t = i18next.getFixedT(language);
  return { ...createAccessors(t), t };
};
```

Only the very first call ever reaches `i18next.init()`; every other call (including a same-language repeat) reads through `getFixedT`, which never touches `changeLanguage`/`loadResources`. This is safe because `dantalion-i18n`'''s `initResources()` unconditionally merges **both** `en` and `ja` into the resources map regardless of the requested `lng`, so both locales''' data is already resident after that first init.

Scope, unchanged from the draft:

- `packages/web/src/lib/dantalion.ts`: replace the always-re-resolve `getAccessorsFor` with the shared-promise version above; import `i18next` directly and `createAccessors` from `@kurone-kito/dantalion-i18n` (already exported).
- `packages/web/package.json`: add `"i18next": "26.2.0"` to `dependencies` (pinned to the version `dantalion-i18n` resolves, so both consumers share one module instance).
- New e2e spec (or an addition to `e2e/ssg-i18n.spec.ts`): assert zero `pageerror` events across the genius detail routes (`/en/<N>/`, `/ja/<N>/`), the legacy `/<N>.html` alias, and a result-triple route.

Verification: the manual repro harness confirms the current crash live (headless Chromium + `build`+`preview`), so the same harness (plus the new e2e spec once the fix lands) is the pass/fail signal. Then `pnpm lint` / `pnpm test` / `pnpm --filter @kurone-kito/dantalion-web-demo-web run build` / `test:e2e`.

**Comment by kurone-kito** [comment]
**Correction to the B2 plan above**

The earlier root-cause read (i18next v26 delegating to `changeLanguage()` only on a *second* `init()` call) was wrong — instrumentation showed the crash on the very first, only call in a fresh browser realm, so the shared-promise/`getFixedT` fix in that plan targeted a non-existent problem and was discarded before implementation.

**Actual root cause**: `@solidjs/router`'''s `createAsync` (used by `GeniusDetailPage`) temporarily replaces the global `Promise` (and `fetch`) with a non-functional `MockPromise` stub for the synchronous portion of a resource fetcher'''s first invocation during client-side hydration, to suppress a redundant refetch of already-serialized SSR data (see `@solidjs/router`'''s `createAsync.js`, `subFetch()`). `dantalion-i18n`'''s `createTAsync` -> `i18next.init()` constructs its own bookkeeping `new Promise(...)` synchronously inside that window; under the stub, the executor never runs, so `resolve`/`reject` are never captured and i18next'''s internal `changeLanguage` -> `loadResources` -> `done()` throws `i.resolve is not a function` when it later calls `deferred.resolve(...)`.

**Fix (implemented)**: add a single `await undefined;` at the top of `getAccessorsFor` in `packages/web/src/lib/dantalion.ts`, before calling `createAccessorsAsync`. `await` on a plain value always resolves through the realm'''s intrinsic `%Promise%`, never the mutable global binding, so this yields past the hydration-mock window (which is scoped to the fetcher'''s synchronous portion only) before `i18next.init()`'''s own `new Promise(...)` runs. Verified live with a headless Chromium against `build`+`preview`: the `i.resolve is not a function` pageerror is gone on `/en/100/`, `/ja/919/`, and `/100.html`, with identical localized content. The result-triple route (`/en/result/<triple>/`) was never affected -- it loads via plain `solid-js` `createResource`, not `@solidjs/router`'''s `createAsync`, so the hydration-time Promise mock never applies there.

Added `e2e/console-errors.spec.ts` asserting zero `pageerror` events across all four acceptance-criteria routes. No new dependencies; no upstream `dantalion-i18n` change needed.

**Comment by kurone-kito** [comment]
_claude-idd-fork-20260920: issue claim released — IDD automation marker. Do not edit._
